import { 
    FileText,
   ClipboardCheck,
  Clipboard,
  Settings,
  Sparkles,
  Bot,
  Search,
  Shield,
  Lock,
  Cloud,
  Layers,
  Tag,
  MessageSquare,
  BookOpen,
  Table,
  CheckSquare,
  FileSpreadsheet,
  BrainCircuit,
} from "lucide-react";


export const APP_BACKGROUND_ICONS = [
  { icon: Sparkles, position: "top-[6%] left-[6%]" },
  { icon: MessageSquare, position: "top-[4%] left-[92%]" },
  { icon: Shield, position: "top-[12%] left-[78%]" },
  { icon: Settings, position: "top-[10%] left-[34%]" },
  { icon: FileText, position: "top-[24%] left-[15%]" },
  { icon: Cloud, position: "top-[20%] left-[88%]" },
  { icon: BookOpen, position: "top-[30%] left-[60%]" },
  { icon: ClipboardCheck, position: "top-[38%] left-[4%]" },
  { icon: Bot, position: "top-[36%] left-[95%]" },
  { icon: Tag, position: "top-[48%] left-[24%]" },
  { icon: Layers, position: "top-[50%] left-[85%]" },
  { icon: BrainCircuit, position: "top-[58%] left-[10%]" },
  { icon: Search, position: "top-[62%] left-[68%]" },
  { icon: Lock, position: "top-[70%] left-[3%]" },
  { icon: Clipboard, position: "top-[68%] left-[92%]" },
  { icon: Table, position: "top-[80%] left-[18%]" },
  { icon: FileSpreadsheet, position: "top-[82%] left-[80%]" },
  { icon: CheckSquare, position: "top-[92%] left-[45%]" },
  { icon: Sparkles, position: "top-[94%] left-[8%]" },
  { icon: MessageSquare, position: "top-[90%] left-[95%]" },
];
