import mongoose from "mongoose";
import * as documentChunkRepository from "../processing/documentChunk.repository.js";

/**
 * Retrieval layer for RAG chat — the bridge between a question's
 * embedding (generated by the AI service) and the chunks that answer
 * it (found by Atlas Vector Search, which stays entirely backend-side).
 *
 * Thin by design: permission resolution happens upstream in
 * rag.service.js, the actual $vectorSearch lives in the repository —
 * this service's job is normalizing inputs and owning retrieval policy
 * (how the allowed-document scope is applied, defaults like topK).
 */

/**
 * Returns the topK most relevant chunks across the allowed documents,
 * ordered by relevance score (highest first). Each chunk is
 * { _id, documentId, chunkIndex, text, score }.
 */
export const retrieveRelevantChunks = async ({ queryEmbedding, allowedDocumentIds, topK }) => {
  if (!allowedDocumentIds || allowedDocumentIds.length === 0) {
    // A user with no accessible documents retrieves nothing — the AI
    // service will answer "not enough information" from empty context
    // rather than this being an error.
    return [];
  }

  // $vectorSearch filters compare by exact BSON type: a string id would
  // silently match nothing, so normalize every id to ObjectId here at
  // the boundary rather than trusting each caller.
  const documentObjectIds = allowedDocumentIds.map((id) =>
    typeof id === "string" ? new mongoose.Types.ObjectId(id) : id
  );

  return documentChunkRepository.vectorSearchChunks({
    queryEmbedding,
    allowedDocumentIds: documentObjectIds,
    topK,
  });
};
